# --- Taps ---
tap "OJFord/formulae"

# --- CLI tools ---
brew "bat"
brew "curl"
brew "ctags"
brew "diff-so-fancy"
brew "eza"
brew "fd"
brew "gh"
brew "git"
brew "loginitems"
brew "mise"
brew "neovim"
brew "ripgrep"
brew "shellcheck"
brew "tree-sitter-cli"
brew "zoxide"
brew "zplug"
brew "zsh"

# --- GUI apps ---
cask "1password"
cask "1password-cli"
cask "beeper"
cask "claude"
cask "dropbox"
cask "font-fira-code-nerd-font"
cask "ghostty"
cask "hammerspoon"
cask "karabiner-elements"
cask "jordanbaird-ice"
cask "notion"
cask "notion-calendar"
cask "obs"
cask "obsidian"
cask "perplexity"
cask "raycast"
cask "slack"
cask "spotify"
cask "soulver"
cask "todoist-app"
cask "wispr-flow"
cask "zen"
cask "zoom"
